### PR TITLE
Add calculated sha256sum to stable_diffusion.json

### PR DESCRIPTION
**Pull request by ikmckenz**
I wrote a simple script to download every model, calculate the sha256sum, and insert it into the file config. These hashes match the sha256sum reported by HuggingFace, for HF models.
There are two seperate commits:
1. The first one is only a whitespace formatting change, it puts consistent formatting across the stable diffusion json file (there were at least three different whitespace indentations across the file), this makes them all 2 space indent consistent with the Node.js style.
2. The second commit adds the calculated sha256 hashes, which match HF.

Hopefully having these two commits separate allows for easier review of the large change. If the reviewers want I could probably revert the first commit and keep the inconsistent formatting.

The script I used to download the models and calculate the hashes uses [my proposed SHA256 hashing change to Natali](https://github.com/db0/nataili/pull/4). I paste the script here, in case the reviewers also want to run it and ensure the hashes provided are correct. 

```python
import json
import os
from time import gmtime, strftime

import requests

from nataili.model_manager.base import BaseModelManager

CURRENT_MODELS = "https://raw.githubusercontent.com/db0/AI-Horde-image-model-reference/main/stable_diffusion.json"


def main():
    models = requests.get(CURRENT_MODELS).json()
    for model in models:
        print(model, strftime("%Y-%m-%d %H:%M:%S", gmtime()))
        try:
            download_link = models[model]["config"]["download"][0]["file_url"]
            downloaded_file = requests.get(download_link)
            file_name = models[model]["config"]["download"][0]["file_name"]
            with open(file_name, "wb") as f:
                f.write(downloaded_file.content)
            calculated_sha265sum = BaseModelManager.get_file_sha256_hash(file_name)
            models[model]["config"]["files"][0]["sha256sum"] = calculated_sha265sum
            os.remove(file_name)
        except:
            print("failed on {}".format(model))

    with open("stable_diffusion.json", "w") as f:
        json.dump(models, f)


def cleanup():
    # Remove cached hash files
    FILEPATTERN = "^.*\.(md5|sha256)$"
    import re
    for f in os.listdir("."):
        if re.search(FILEPATTERN, f):
            os.remove(f)


if __name__ == "__main__":
    main()
    cleanup()
```

### CODE REVIEW

**Comment by ResidentChief** [comment]
What purpose does having the sha256 have that the md5 doesn't serve?

**Comment by ikmckenz** [comment]
I think it's a useful improvement for the following reasons:

1. Both HuggingFace and Civitai do not use MD5, but do use SHA256. So having these SHA256 sums allows people to check against the reported hashes from those websites. 
2. MD5 is a weak algorithm that has been considered broken since 2010. In many use cases this is fine, since cryptographic hashes aren't necessary, but I believe in this case a move to a secure hashing function is justified. A multi GB pickle file which is expected to have large amounts of random looking data is the perfect file type for creating malware that has a hash collision.

**Comment by db0** [comment]
I'm OK with that, but only if the main maintainer @AlRlC is OK with maintaining that hash as well ,or if you or someone else willing to help.

**Comment by db0** [comment]
The relevant PR is merged into the worker

**Pull request merged**
