### PR TITLE
Add a bunch of showcases, add missing showcases from db.json to stable_diffusion.json

### PR DESCRIPTION
**Pull request by anonderpling**
I went through the entire discord channel (or rather, I went back to [\[1:56 PM\]Jug: I believe the only missing showcases are now: Sygil-Dev Diffusion pix2pix](https://discord.com/channels/781145214752129095/1040781036595974204/1072999491671707669)) and added all of those here

-----

showcase for duchaiten classic anime:

all

prompts:
- a dark and brooding vampire temple
- a fox girl smelling a bouquet of flowers, half-body portrait
- a full body portrait of a cyborg holding a sniper rifle
- a scene of a pig sitting in a chair at a formal dinner
- a vampire princess floating in front of a full moon
- kane from c&c &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ... I tried, but he doesn't have a last name
- a frog prince &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ... I was going to complain until I remembered what 80s anime boys look like
- paddington bear &nbsp;&nbsp;&nbsp;&nbsp; ... lol
- Yuriko Omega &nbsp;&nbsp;&nbsp; &nbsp; &nbsp; ... [not](https://cnc.fandom.com/wiki/Yuriko_Omega/Profile?file=Yuriko_Omega_RA3U_Menu_Screen.jpg) [even](https://cnc.fandom.com/wiki/Yuriko_Omega/Profile?file=Yuriko_Omega_Poster.jpg) [close](http://web.archive.org/web/20110203080621im_/http://portal.commandandconquer.com/SiteAssets/redalert/images/ra3-uprising-bg-base.jpg), not that I expected better

### CODE REVIEW

**Comment by anonderpling** [comment]
Added the other PR with fixed showcases for stable_diffusion.json (#15)

Added neverending dream showcase:
all

**Comment by anonderpling** [comment]
Added muted001's showcase for Rev Animated (I didn't make this one)

image-grid

**Comment by anonderpling** [comment]
Added voodoocode's Fking SciFi showcase. I didn't make this one either. Also added the existing showcase to the other file.

02_voodoocode

**Comment by anonderpling** [comment]
Added voodoocode's showcase for RealBiter

all

**Comment by anonderpling** [comment]
Added muted001's [Illuminati showcase](https://discord.com/channels/781145214752129095/1040781036595974204/1080718135444905984)

showcase

**Comment by anonderpling** [comment]
Added muted001's showcases for [woop woop photo](https://discord.com/channels/781145214752129095/1040781036595974204/1079514440497639496) and [rachel walker watercolors](https://discord.com/channels/781145214752129095/1040781036595974204/1074434177614745621):

woop woop
watercolors

**Comment by anonderpling** [comment]
Added `᲼᲼᲼᲼`'s showcase for illuminati

**Comment by anonderpling** [comment]
Fixed the removed models. Added muted001's [neverending dream](https://discord.com/channels/781145214752129095/1040781036595974204/1083588848891744306)

**Comment by anonderpling** [comment]
Added muted001 [realism engine](https://discord.com/channels/781145214752129095/1040781036595974204/1084137922082648135)

**Comment by anonderpling** [comment]
Added [muted001's expmix showcase](https://discord.com/channels/781145214752129095/1040781036595974204/1085040515982037063)

**Comment by AlRlC** [comment]
Thank you so much for keeping up with these, will review now

**Pull request merged**
